### ISSUE TITLE
Looking up many values causes API throttling

### ISSUE THREAD

**Issue by lordnynex** [deanwilson/ansible-plugins#1]
Hello,

I'm using your cloudformation lookup plugin. It's really great! I needed to fetch multiple values from the stack outputs and this caused failure due to API rate limiting on Amazon's side.

**Comment by deanwilson** [comment]
Glad to know it's a helpful lookup. If you need to access more than a few values from a stack I recommend you use https://github.com/deanwilson/ansible-plugins#cloudformation_stack_facts instead of the lookup. It's faster and hits the API less.
